# Generated by Django 4.2.9 on 2024-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorental', '0003_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cubreterceros', models.BooleanField(default=True)),
                ('montoquecubre', models.IntegerField()),
                ('nombreseguro', models.CharField(max_length=40)),
            ],
        ),
    ]
